
LANGUAGE_NAME_TO_SHORT_CODE = {
"Afrikaans":"af",      
"Albanian":"sq",      
"Amharic":"am",      
"Arabic":"ar",      
"Armenian":"hy",      
"Assamese":"as",      
"Azerbaijani":"az",      
"Bangla":"bn",      
"Bashkir":"ba",      
"Bosnian (Latin)":"bs",      
"Bulgarian":"bg",      
"Cantonese (Traditional)":"yue",        
"Catalan":"ca",      
"Chinese (Literary)":"lzh",        
"Chinese Simplified":"zh-Hans",          
"Chinese Traditional":"zh-Hant",          
"Croatian":"hr",      
"Czech":"cs",      
"Danish":"da",      
"Dari":"prs",        
"Divehi":"dv",      
"Dutch":"nl",      
"English":"en",      
"Estonian":"et",      
"Fijian":"fj",      
"Filipino":"fil",        
"Finnish":"fi",      
"French":"fr",      
"French (Canada)":"fr-ca",        
"Georgian":"ka",      
"German":"de",      
"Greek":"el",      
"Gujarati":"gu",      
"Haitian Creole":"ht",      
"Hebrew":"he",      
"Hindi":"hi",      
"Hmong Daw":"mww",        
"Hungarian":"hu",      
"Icelandic":"is",      
"Indonesian":"id",      
"Inuinnaqtun":"ikt",        
"Inuktitut":"iu",      
"Inuktitut (Latin)":"iu-Latn",          
"Irish":"ga",      
"Italian":"it",      
"Japanese":"ja",      
"Kannada":"kn",      
"Kazakh":"kk",      
"Khmer":"km",      
"Klingon":"tlh-Lat",          
"Klingon (plqaD)":"tlh-Piq",          
"Korean":"ko",      
"Kurdish (Central)  ":"ku",      
"Kurdish (Northern)":"kmr",        
"Kyrgyz":"ky",      
"Lao":"lo",      
"Latvian":"lv",      
"Lithuanian":"lt",      
"Macedonian":"mk",      
"Malagasy":"mg",      
"Malay ":"ms",      
"Malayalam":"ml",      
"Maltese":"mt",      
"Maori":"mi",      
"Marathi":"mr",      
"Mongolian (Cyrillic)":"mn-Cyrl",          
"Mongolian (Traditional)":"mn-Mong",          
"Myanmar":"my",      
"Nepali":"ne",      
"Norwegian":"nb",      
"Odia":"or",      
"Pashto":"ps",      
"Persian ":"fa",      
"Polish":"pl",      
"Portuguese (Brazil)":"pt",      
"Portuguese (Portugal)":"pt-pt",        
"Punjabi":"pa",      
"Queretaro Otomi":"otq",        
"Romanian":"ro",      
"Russian":"ru",      
"Samoan":"sm",      
"Serbian (Cyrillic)":"sr-Cyrl",          
"Serbian (Latin)":"sr-Latn",          
"Slovak":"sk",      
"Slovenian":"sl",      
"Spanish":"es",      
"Swahili":"sw",      
"Swedish":"sv",      
"Tahitian":"ty",      
"Tamil":"ta",      
"Tatar":"tt",      
"Telugu":"te",      
"Thai":"th",      
"Tibetan":"bo",      
"Tigrinya":"ti",      
"Tongan":"to",      
"Turkish":"tr",      
"Turkmen":"tk",      
"Ukrainian":"uk",      
"Upper Sorbian":"hsb",        
"Urdu":"ur",      
"Uyghur":"ug",      
"Uzbek (Latin)":"uz",      
"Vietnamese":"vi",      
"Welsh":"cy",      
"Yucatec Maya":"yua",                           
                         
}
CHUNK_SIZE = 15
LANGUAGE_SHORT_CODE_TO_NAME = {value: key for key, value in LANGUAGE_NAME_TO_SHORT_CODE.items()}

LOWERCASE_LANGUAGENAME = {
    
"afrikaans":"af",      
"albanian":"sq",      
"amharic":"am",      
"arabic":"ar",      
"armenian":"hy",      
"assamese":"as",      
"azerbaijani":"az",      
"bangla":"bn",      
"bashkir":"ba",      
"bosnian (latin)":"bs",      
"bulgarian":"bg",      
"cantonese (traditional)":"yue",        
"catalan":"ca",      
"chinese (literary)":"lzh",        
"chinese simplified":"zh-hans",          
"chinese traditional":"zh-hant",          
"croatian":"hr",      
"czech":"cs",      
"danish":"da",      
"dari":"prs",        
"divehi":"dv",      
"dutch":"nl",      
"english":"en",      
"estonian":"et",      
"fijian":"fj",      
"filipino":"fil",        
"finnish":"fi",      
"french":"fr",      
"french (canada)":"fr-ca",        
"georgian":"ka",      
"german":"de",      
"greek":"el",      
"gujarati":"gu",      
"haitian creole":"ht",      
"hebrew":"he",      
"hindi":"hi",      
"hmong daw":"mww",        
"hungarian":"hu",      
"icelandic":"is",      
"indonesian":"id",      
"inuinnaqtun":"ikt",        
"inuktitut":"iu",      
"inuktitut (latin)":"iu-latn",          
"irish":"ga",      
"italian":"it",      
"japanese":"ja",      
"kannada":"kn",      
"kazakh":"kk",      
"khmer":"km",      
"klingon":"tlh-lat",          
"klingon (plqad)":"tlh-piq",          
"korean":"ko",      
"kurdish (central)  ":"ku",      
"kurdish (northern)":"kmr",        
"kyrgyz":"ky",      
"lao":"lo",      
"latvian":"lv",      
"lithuanian":"lt",      
"macedonian":"mk",      
"malagasy":"mg",      
"malay ":"ms",      
"malayalam":"ml",      
"maltese":"mt",      
"maori":"mi",      
"marathi":"mr",      
"mongolian (cyrillic)":"mn-cyrl",          
"mongolian (traditional)":"mn-mong",          
"myanmar":"my",      
"nepali":"ne",      
"norwegian":"nb",      
"odia":"or",      
"pashto":"ps",      
"persian ":"fa",      
"polish":"pl",      
"portuguese (brazil)":"pt",      
"portuguese (portugal)":"pt-pt",        
"punjabi":"pa",      
"queretaro otomi":"otq",        
"romanian":"ro",      
"russian":"ru",      
"samoan":"sm",      
"serbian (cyrillic)":"sr-cyrl",          
"serbian (latin)":"sr-latn",          
"slovak":"sk",      
"slovenian":"sl",      
"spanish":"es",      
"swahili":"sw",      
"swedish":"sv",      
"tahitian":"ty",      
"tamil":"ta",      
"tatar":"tt",      
"telugu":"te",      
"thai":"th",      
"tibetan":"bo",      
"tigrinya":"ti",      
"tongan":"to",      
"turkish":"tr",      
"turkmen":"tk",      
"ukrainian":"uk",      
"upper sorbian":"hsb",        
"urdu":"ur",      
"uyghur":"ug",      
"uzbek (latin)":"uz",      
"vietnamese":"vi",      
"welsh":"cy",      
"yucatec maya":"yua",    
    
}
LOWERCASE_LANGUAGE_SHORT_CODE_TO_NAME = {value: key for key, value in LOWERCASE_LANGUAGENAME.items()}
TRANSLATE_API_URL = "https://api.cognitive.microsofttranslator.com/translate"