export enum BotAuthClaims
{
    designatedChannelView = "designated_channel_view",
    designatedChannelModify = "designated_channel_modify",
    customPrefixSet = "custom_prefix_set",
    welcomeMessageView = "welcome_message_view",
    welcomeMessageModify = "welcome_message_modify",
    tagAdd = "tag_add",
    tagDelete = "tag_delete",
    assignableRolesAdd = "assignable_roles_add",
    assignableRolesDelete = "assignable_roles_delete",
    deleteMessage = "delete_message",
    emoteAdd = "emote_add",
    claimsView = "claims_view",
    claimsModify = "claims_modify",
    manageClassAdd = "manage_class_add",
    moderationWarn = "moderation_warn",
    moderationBan = "moderation_ban",
    moderationMute = "moderation_mute",
    moderationPurge = "moderation_purge",
    moderationInfractionView = "moderation_infraction_view",
    moderationInfractionViewSelf = "moderation_infraction_view_self",
    dashboardView = "dashboard_view",
    dashboardEdit = "dashboard_edit",
    guildSettingsView = "guild_settings_view",
    guildSettingsEdit = "guild_settings_edit"
}