namespace ClemBot.Api.Common.Enums;

public enum BotAuthClaims
{
    designated_channel_view,
    designated_channel_modify,
    custom_prefix_set,
    welcome_message_view,
    welcome_message_modify,
    tag_add,
    tag_delete,
    assignable_roles_add,
    assignable_roles_delete,
    delete_message,
    emote_add,
    claims_view,
    claims_modify,
    manage_class_add,
    moderation_warn,
    moderation_ban,
    moderation_mute,
    moderation_purge,
    moderation_infraction_view,
    moderation_infraction_view_self,
    dashboard_view,
    dashboard_edit,
    guild_settings_view,
    guild_settings_edit,
    custom_tag_prefix_set,
}
