name: ClemBot.Bot Prod Deployment

on:
  push:
    branches: [ master ]
    paths: 
      - "ClemBot.Bot/**"
  pull_request:
    branches: [ master ]
    paths: 
      - "ClemBot.Bot/**"
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual ClemBot workflow trigger'
        required: true
        default: 'Manual Deployment'

jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v2
            - name: Run Deploy Commands
              run: |
                cd ~/ClemBot
                git pull origin master
                docker-compose up -d --force-recreate --no-deps --build clembot.bot
            - name: Discord notification
              env:
                DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
              uses: "Ilshidur/action-discord@0.3.0"
              with:
                args: 'The project {{ EVENT_PAYLOAD.repository.full_name }}/ClemBot.Bot has been deployed.'
