# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ClemBot.Bot Master integration

on:
  push:
    branches: [ master ]
    paths: 
      - "ClemBot.Bot/**"
  pull_request:
    branches: [ master ]
    paths: 
      - "ClemBot.Bot/**"
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ClemBot.Bot
    steps:
    - uses: actions/checkout@v2