name: ClemBot.Api Master integration

on:
  push:
    branches: [ master ]
    paths: 
      - "ClemBot.Api/**"
  pull_request:
    branches: [ master ]
    paths: 
      - "ClemBot.Api/**"
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ClemBot.Api
    steps:
    - uses: actions/checkout@v2