name: ClemBot Master Deployment

on:
  push:
    branches: [ master ]
    paths: 
      - "bot/**"
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual ClemBot workflow trigger'
        required: true
        default: 'Manual Deployment'

jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v2
            - name: Run Deploy Script
              run: ~/deploy.sh
            - name: Discord notification
              env:
                DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
              uses: "Ilshidur/action-discord@0.3.0"
              with:
                args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
