name: ClemBot Master Deployment

on:
  push:
    branches: [ master ]

jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v2
            - name: Run Deploy Script
              run: ~/deploy.sh
            - uses: actions/setup-ruby@v1
            - name: Send Webhook Notification
              if: always()
              env:
                JOB_STATUS: ${{ job.status }}
                WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
                HOOK_OS_NAME: ${{ runner.os }}
                WORKFLOW_NAME: ${{ github.workflow }}
              run: |
                git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
                bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
              shell: bash
