name: ClemBot Master Deployment

on:
  push:
    branches: [ master ]

jobs:
    deploy:
        needs: build
        name: Deploy
        runs-on: [self-hosted]
    
        steps:
            - uses: actions/checkout@v2
            - name: Run Deploy Script
              run: ~/deploy.bat
