name: ClemBot Master Deployment

on:
  push:
    branches: [ master ]

jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v2
            - name: Run Deploy Script
              run: ~/deploy.sh
            - uses: actions/setup-ruby@v1
            - name: Discord notification
            env:
              DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
            uses: Ilshidur/action-discord@master
            with:
              args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
