on:
  workflow_run:
    workflows: [ ClemBot.Bot-integration ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  on-lint-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const owner = "ClemBotProject";
            const repo = "ClemBot";

            const {
              data: { artifacts },
            } = await github.request("GET /repos/{owner}/{repo}/actions/artifacts", {
              owner,
              repo,
            });

            try {
              let { headers } = await github.request(
                "HEAD /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}",
                {
                  owner,
                  repo,
                  artifact_id: artifacts[0].id,
                  archive_format: "zip",
                  request: {
                    redirect: "manual",
                  },
                }
              );
              console.log(headers.location);
            } catch (error) {
              console.log(error);
            }
            github.request(headers.location)
              .pipe(fs.createWriteStream('lint-errors.zip'))
              .on('close', function () {
                console.log('File written!');
              });
      - shell: bash
        run: |
          apt-get install unzip
          unzip lint-errors.zip
          echo ${{ github.event.workflow_run.artifacts_url}}
          ls
          ls lint_errors