on:
  workflow_run:
    workflows: [ ClemBot.Bot-integration ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  on-lint-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: lint-errors
          workflow: ClemBot.Bot-integration
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow_conclusion: failure
          commit: ${{github.event.pull_request.head.sha}}


      - shell: bash
        run: |
          ls
          ls lint_errors