on:
  workflow_run:
    workflows: [ ClemBot.Bot-integration ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  on-lint-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const {
              data: { artifacts },
            } = await github.request("GET /repos/{owner}/{repo}/actions/artifacts", {
              ClemBotProject,
              ClemBot,
            });

            try {
              let { headers } = await github.request(
                "HEAD /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}",
                {
                  ClemBotProject,
                  ClemBot,
                  artifact_id: artifacts[0].id,
                  archive_format: "zip",
                }
              );
              console.log(headers.location);
            } catch (error) {
              console.log(error);
            }
      - shell: bash
        run: |
          echo ${{ github.event.workflow_run.artifacts_url}}
          ls
          ls lint_errors