on:
  workflow_run:
    workflows: [ ClemBot.Bot-integration ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  on-lint-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "First workflow was a failure"
      
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: lint-error
          search_artifacts: true


      - shell: bash
        run: |
          ls
          ls lint_errors