on:
  workflow_run:
    workflows: [ ClemBot.Bot-integration ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  on-lint-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "First workflow was a failure"
      
      - name: Download lint errors
        uses: actions/download-artifact@v3
        with:
          name: lint-errors

      - shell: bash
        run: |
          ls
          ls lint_errors